Server/NabuNet/Controllers/HomeController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using NabuNet.Models;
using SixLabors.ImageSharp.ColorSpaces;

namespace NabuNet.Controllers;

public class HomeController : NabuControllerBase
{
    private readonly ILogger _logger;
    private readonly IServerConfigFactory _Settings;

    public HomeController(ILogger<HomeController> logger, IServerConfigFactory settings)
    {
        _logger = logger;
        _Settings = settings;
    }

    public async Task<IActionResult> About([FromServices] IEnumerable<ILibraryCredits> creditsFrom)
    {
        var data = new AboutPageModel() { Version = this.GetType().Assembly.GetName()?.Version?.ToString() ?? "?" };
        var list = new List<Tuple<string, IEnumerable<LibraryInfo>>>();
        foreach (var cf in creditsFrom)
        {
            var tp = new List<LibraryInfo>();
            var credits = await cf.GetLirbaryInfoAsync();
            tp.AddRange(credits.OrderBy(x => x.Name));
            if (tp.Count > 0)
            {
                list.Add(new Tuple<string, IEnumerable<LibraryInfo>>(cf.Category, tp));
            }
        }
        data.Libraries = list.OrderBy(x => x.Item1).ToList();

        var cfg = await _Settings.GetOrLoad();

        data.Imprint = cfg.Imprint;

        return View(data);
    }

    public IActionResult Index()
    {
        return View();
    }

    public async Task<IActionResult> Status()
    {
        var msg = (await _Settings.GetOrLoad()).ServerMessage;
        return View(msg);
    }

    public async Task<IActionResult> Privacy()
    {
        string policy = await (await _Settings.GetOrLoad()).GetPrivacyPolicy();
        return View((object)policy);    // string as model...
    }

    public async Task<IActionResult> Terms()
    {
        string terms = await (await _Settings.GetOrLoad()).GetTermsOfService();
        return View((object)terms);    // string as model...
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Server/NabuNet/ServerInfoViewComponent.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace NabuNet
{
    public class ServerInfoViewComponent
        : ViewComponent
    {
        private readonly IServerConfigFactory _config;

        public ServerInfoViewComponent(IServerConfigFactory config)
        {
            _config = config;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var cfg = await _config.GetOrLoad();
            return View("HeadLine", cfg);
        }


    }
}

Server/NabuNet/Views/Home/About.cshtml
@model AboutPageModel
@{
    ViewData["Title"] = "About";
}
<vc:server-info />

@if (Model.Imprint != null)
{
    <h2>@Model.Imprint.Title</h2>
    <markdown content="@Model.Imprint.Article"></markdown>
}

<h2>Software</h2>
<p>This server runs version @Model.Version. NabuNet server was developed by Atkelar in 2023.</p>
<p>The server thinks that the time is @(System.DateTime.Now.ToLongTimeString()) locally, and
    @(System.DateTime.UtcNow.ToLongTimeString()) UTC.</p>
<h3>Extra credits</h3>
@foreach (var item in Model.Libraries)
{
    <h4>@item.Item1</h4>
    <ul>
    @foreach (var cItem in item.Item2)
        {
            <li><strong>@cItem.Name</strong>
                @if (cItem.Version != null)
                {
                    <text> - </text> <span>(@cItem.Version)</span>
                }
                @if (cItem.Comment != null)
                {
                    <br />
                    @cItem.Comment
                }
                @if (cItem.LicenseUri != null)
                {
                <br />
                Info:
                    <a href="@cItem.LicenseUri">@cItem.LicenseUri</a>
                }
            </li>
        }
    </ul>
}

Server/NabuNet/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}

<vc:server-info />
<div class="logo-container">
    <img src="~/images/logo.png">
    <p>
        Welcome!
    </p>
</div>

Server/NabuNet/Views/Home/Status.cshtml
@model BaseArticle?
@{
    ViewData["Title"] = "Server Status";
}

@if (Model == null)
{
    <h1 class="display-4">Current status...</h1>
    <p>...there is no active announcement!</p>
}
else
{
    <h1 class="display-4">@Model.Title</h1>
    <markdown class="infoarea" content="@Model.Article"></markdown>
    @if (Model.ReferenceDate.HasValue)
    {
        <p>The information is about <time
        absolute="@Model.ReferenceDate"></time>, which is <time
        relative="@Model.ReferenceDate"></time>.</p>
    }
}
</div>

Server/NabuNet/Views/Home/Terms.cshtml
@model string
@{
    ViewData["Title"] = "Terms of Service";
}

<markdown content="@Model"></markdown>